
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.compiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int SLASH = 5;
  public static final int INTEGER = 11;
  public static final int PARENTHESISC = 7;
  public static final int EQUAL = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ASTERISK = 4;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int SEMICOLON = 9;
  public static final int PARENTHESISO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "ASTERISK",
  "SLASH",
  "PARENTHESISO",
  "PARENTHESISC",
  "EQUAL",
  "SEMICOLON",
  "ID",
  "INTEGER"
  };
}

